Repository prgrms-be-devcourse/NBE4-5-3-Team07, pull requests merged in 2025-04, with the labels that each got.

#7 Refactor/#1: chat, mail migration
  .idea/NBE4-5-3-Team07.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  backend/build.gradle.kts
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/controller/ChatController.java
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/controller/ChatController.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/model/ChatRoom.java
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/model/ChatRoom.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/model/Message.java
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/model/Message.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/service/ChatPublisher.java
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/service/ChatPublisher.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/service/ChatService.java
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/service/ChatService.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/service/ChatSubscriber.java
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/service/ChatSubscriber.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/mail/EmailService.java
  backend/src/main/java/com/java/NBE4_5_3_7/domain/mail/EmailService.kt
  backend/src/test/java/com/java/NBE4_5_3_7/domain/chat/chatServiceTest.kt
  backend/src/test/java/com/java/NBE4_5_3_7/domain/mail/EmailServiceTest.kt
Labels: Refcator

#10 [refactor&fix] global migration & Member Id bug fix
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/service/ChatService.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/community/controller/CommunityController.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/member/entity/Member.java
  backend/src/main/java/com/java/NBE4_5_3_7/domain/member/entity/Member.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/java/NBE4_5_3_7/domain/member/repository/MemberRepository.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/member/service/MemberService.java
  backend/src/main/java/com/java/NBE4_5_3_7/domain/member/service/MemberService.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/app/AppConfig.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/app/AppConfig.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/AsyncConfig.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/AsyncConfig.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/OpenApiConfig.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/OpenApiConfig.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/PortOneConfig.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/PortOneConfig.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/RedisConfig.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/RedisConfig.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/RedissonConfig.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/RedissonConfig.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/SchedulerConfig.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/SchedulerConfig.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/WebSocketConfig.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/config/WebSocketConfig.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/customAnnotation/PremiumAccess.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/customAnnotation/PremiumAccess.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/customAnnotation/SubscriptionPlanChecker.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/customAnnotation/SubscriptionPlanChecker.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/dataInit/InterviewContentDataInit.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/dto/RsData.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/dto/RsData.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/entity/BaseEntity.java
  backend/src/main/java/com/java/NBE4_5_3_7/global/entity/BaseEntity.kt
Labels: Fix, Refcator

#20 Feat/#18
  backend/build.gradle.kts
  backend/src/main/java/com/java/NBE4_5_3_7/domain/community/like/repository/PostLikeRepository.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/community/post/service/PostService.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/member/service/MemberService.kt
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/java/NBE4_5_3_7/domain/community/post/service/PostServiceTest.kt
  frontend/src/app/payment/result/page.tsx
Labels: Test

#25 Test/#23: InterviewComment 단위 테스트
  backend/src/test/java/com/java/NBE4_5_3_7/domain/interviewComment/service/InterviewCommentServiceTest.kt
Labels: Test

#44 test/#31: 인증 인가 토큰 테스트, 보안 권한 설정 변경
  backend/src/main/java/com/java/NBE4_5_3_7/domain/member/service/AuthTokenService.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/member/service/MemberService.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/security/SecurityConfig.kt
  backend/src/test/java/com/java/NBE4_5_3_7/domain/member/service/AuthTokenServiceTest.java
  backend/src/test/java/com/java/NBE4_5_3_7/domain/member/service/AuthTokenServiceTest.kt
Labels: Fix, Test

#45 Test/#28
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/controller/StudyMemoController.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/controller/StudyMemoLikeController.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/dto/request/StudyMemoRequestDto.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/entity/StudyContent.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/repository/StudyMemoRepository.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/service/StudyMemoLikeService.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/service/StudyMemoService.kt
  backend/src/main/resources/application-test.yml
  backend/src/test/java/com/java/NBE4_5_3_7/domain/news/NewsServiceTest.kt
  backend/src/test/java/com/java/NBE4_5_3_7/domain/payment/PaymentServiceTest.kt
  backend/src/test/java/com/java/NBE4_5_3_7/domain/study/StudyContentAdminServiceTest.kt
  backend/src/test/java/com/java/NBE4_5_3_7/domain/study/StudyContentServiceTest.kt
  backend/src/test/java/com/java/NBE4_5_3_7/domain/study/StudyMemoLikeServiceTest.kt
  backend/src/test/java/com/java/NBE4_5_3_7/domain/study/StudyMemoServiceTest.kt
Labels: Test

#57 Test: Interview 도메인 통합 테스트 추가 및 테스트 환경 개선
  backend/build.gradle.kts
  backend/src/main/java/com/java/NBE4_5_3_7/global/security/SecurityConfig.kt
  backend/src/main/resources/application-test.yml
  backend/src/test/java/com/java/NBE4_5_3_7/domain/interview/InterviewTest.kt
  frontend/package-lock.json
Labels: Test

#59 Feat/#58
  backend/src/main/java/com/java/NBE4_5_3_7/domain/community/post/service/PostService.kt
  docker-compose.yml
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Refcator

#60 feat: 채팅 내역 영속성 부과#56
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/entity/ChatMessageEntity.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/repository/ChatMessageRepository.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/chat/service/ChatService.kt
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#61 Refactor/#54
  backend/src/main/java/com/java/NBE4_5_3_7/domain/news/dto/responseDto/JobResponseDto.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/news/dto/responseDto/JobsDetailDto.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/news/dto/responseDto/NewResponseDto.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/news/service/NewsService.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/payment/dto/responseDto/PaymentResponseDto.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/payment/service/PaymentService.kt
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/java/NBE4_5_3_7/domain/news/NewsServiceTest.kt
  backend/src/test/java/com/java/NBE4_5_3_7/domain/study/StudyMemoServiceTest.kt
Labels: Refcator, Test

#62 fix: 키워드 질문 조회 쿼리 조건 수정
  backend/src/main/java/com/java/NBE4_5_3_7/domain/interview/repository/InterviewContentRepository.kt
Labels: Fix

#63 Fix: 기술면접 csv 데이터와 면접 질문 tailId 연결 로직 수정
  backend/data/기술면접컨텐츠데이터-종합.csv
  backend/src/main/java/com/java/NBE4_5_3_7/global/dataInit/InterviewContentDataInit.kt
Labels: Fix

#65 fix:로그아웃 쿠키 삭제#64
  backend/src/main/java/com/java/NBE4_5_3_7/global/security/SecurityConfig.kt
Labels: Fix

#69 Fix/#68
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/entity/StudyMemo.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/repository/StudyMemoLikeRepository.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/service/StudyMemoLikeService.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/study/service/StudyMemoService.kt
Labels: Fix

#74 community like 좋아요에 대한 동시성 이슈 완전 해결
  backend/src/main/java/com/java/NBE4_5_3_7/domain/community/controller/CommunityController.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/community/like/entity/PostLike.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/community/post/entity/Post.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/community/post/service/PostLikeTransaction.kt
  backend/src/main/java/com/java/NBE4_5_3_7/domain/community/post/service/PostService.kt
  backend/src/main/java/com/java/NBE4_5_3_7/global/security/SecurityConfig.kt
  backend/src/main/resources/application-local.yml
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Fix, Refcator
